http:
  middlewares:
    basic-auth:
      basicAuth:
        # users:
        #   - "user:$apsdfswWvC/6.$E3FtsfTntPC0wVJ7IUVtX1"
        usersFile: "/run/secrets/htpasswd" #be sure to mount the volume through docker-compose.yml
        realm: "Traefik 2 Basic Auth"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    redirect-to-non-www-https:
      redirectRegex:
        regex: ^https?://(?:www\.)?(.+)
        replacement: https://$${1}
        permanent: true

    rfc1918-ips:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16

    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        #customFrameOptionsValue: "allow-from https:{{env "DOMAINNAME_CLOUD_SERVER"}}" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true # add sslHost to all of the services
        # sslHost: "{{env "DOMAINNAME_CLOUD_SERVER"}}"
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
          # https://community.traefik.io/t/how-to-make-websockets-work-with-traefik-2-0-setting-up-rancher/1732
          # X-Forwarded-Proto: "https"

    nextcloud-secure-headers:
       headers:
        customResponseHeaders:
          X-Robots-Tag: #|
            'none'
          server: ''
    #     customFrameOptionsValue: "SAMEORIGIN" ##### maybe needed for Nextcloud to remove the X-Frame-Options error #######
    #    frameDeny: true
    #    accessControlAllowMethods:
    #      - "GET"
    #      - "OPTIONS"
    #      - "PUT"
        accessControlMaxAge: 100
    #    contentSecurityPolicy: |
    #      default-src 'none'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'
    #    addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
        referrerPolicy: 'no-referrer'
    #    hostsProxyHeaders:
    #      - X-Forwarded-Host
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"

    nextcloud-redirect:
      redirectRegex:
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"

#    authelia:
#      forwardAuth:
#        address: "http://localhost:9091/api/verify?rd=https://login.example.net"
#        trustForwardHeader: true
#        authResponseHeaders:
#          - "Remote-User"
#          - "Remote-Groups"

    compress:
      compress: {}
    
    # https://stackoverflow.com/questions/49717670/how-to-config-upload-body-size-restriction-in-traefik
    buffering:
      buffering:
        maxRequestBodyBytes: 10485760
        memRequestBodyBytes: 2097152
        maxResponseBodyBytes: 10485760
        memResponseBodyBytes: 2097152
        retryExpression: "IsNetworkError() && Attempts() <= 2"
